version : "3.1"

services:
  front:
    container_name : front
    build: ./
    command : npm start
    restart: always
    ports: 
      - "8080:8080"
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
     - "80:80"
    volumes:
    - ./nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
       - front  

       